name: Create Contribute Pull Request

on: create

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  create_pull_request:
    if: ${{ contains(github.ref, 'refs/heads/content/') || endsWith(github.ref, '-content-') }}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Output Branch Name remove the refs/heads/
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Initial commit to branch by bot
        run: |
          git checkout ${{ env.branch }}
          git config --global user.name "ubunchuu[bot]"
          git config --global user.email "159746302+ubunchuu-admin@users.noreply.github.com"
          git commit --allow-empty -m "ci: initial commit by bot"
          git push origin ${{ env.branch }}

      - name: Open PR
        id: open_pr
        run: |
          gh pr create --draft --title "[AUTOMATIC] Contribute: ${{ env.branch }}" --body-file .github/pull_request_template.md
        env:
          GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
